[#20_003]
= #154
:hardbreaks:

*das Glöckchen [глёкхен] / die Glöckchen* - колокольчик

*Пример:*
Liebende. Eine poetische Fabel über die unermessliche Kraft verbundener Herzen.

Zwei Karpfen an einem Windspiel lassen hoch oben am First des buddhistischen Tempels ihre Glöckchen erklingen und schenken einsamen Menschen Hoffnung. Der Legende nach sind die beiden Fische Liebende, die füreinander bestimmt sind - bis zu dem Tag, als einer der beiden anfängt, von dem anderen zu träumen ...

Влюблённые. Поэтическая сказка о беспредельной силе связанных сердец.

Два карпа на музыкальной подвеске высоко над кровлей буддийского храма звенят своими колокольчиками, даря надежду одиноким людям. Согласно легенде, две рыбы - влюблённые, предназначены друг для друга, до того дня, когда одна из них начинает видеть сны о другой.

Ps.
Опять сфотографировал случайно, но меня заинтересовало описание. Эта книга есть на на link:https://amzn.to/2OhOeRw["amazone", window=_blank], в бумажном варианте и в виде электронной версии.

Если вдруг кто-то прочитает, напишите, как вам понравилось!
